NashBitesApp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = "website"

urlpatterns = [
  
  # Django provides a built in url for login:
  # auth/login/ [name='login'] under include('django.contrib.auth.urls')
  # in NashBitesProject urls.py file

  path('', views.Welcome, name='welcome'),
  path('register/', views.Register, name='register'),
  path('home/', views.HomeView ,name='home'),
  path('vendor/', views.VendorView, name='vendor'),
  path('location/', views.Location_List, name='locations'),
  # path('login/', views.Login, name='login'),
  url(r'^profile/(?P<username>[\w.@+-]+)/$', views.ProfileView, name='profile'),
]

NashBitesProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('NashBitesApp.urls'))
]

NashBitesApp/models.py
from django.db import models

# Create your models here.

NashBitesApp/models/image.py
from django.contrib.auth.models import User
from django.db import models

class Image(models.Model):
  """ Model represents vendor stored images """
  image = models.ImageField(upload_to='images')
  vendor = models.ForeignKey(User, on_delete=models.CASCADE)

  class Meta:
    db_table = 'images'

  def __str__(self):
    return self.image

NashBitesApp/models/location.py
from django.contrib.auth.models import User
from django.db import models


class Location(models.Model):
    """ Model represents vendor location info """
    address = models.CharField(max_length=255)

    latitude = models.FloatField(
        null=True,
        blank=True
    )

    longitude = models.FloatField(
        null=True,
        blank=True
    )

    timestamp = models.DateTimeField(auto_now_add=True)

    vendor = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'locations'

    def __str__(self):
        return self.address

NashBitesApp/models/profile.py
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
  """ Model represents vendor profile info """
  vendor = models.OneToOneField(User, on_delete=models.CASCADE)
  company_name = models.CharField(max_length=50)
  website_url = models.URLField(blank=True)
  twitter_handle = models.CharField(max_length=10, blank=True)
  instagram_handle = models.CharField(max_length=10, blank=True)
  facebook_handle = models.CharField(max_length=10, blank=True)

  class Meta:
    db_table = 'profile'

  def __str__(self):
    return self.company_name

NashBitesApp/forms/location_form.py
from NashBitesApp.models import Location
from django import forms
# from django.conf import settings


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = [
            'address',
            'latitude',
            'longitude'
        ]
        labels = {
            'address': '',
            'latitude': '',
            'longitude': '',
        }
        widgets = {
            'address': forms.TextInput(attrs={'placeholder': 'Enter an address. . .'}),
            'latitude': forms.NumberInput(attrs={'placeholder': 'Auto generated latitude. . .'}),
            'longitude': forms.NumberInput(attrs={'placeholder': 'Auto generated longitude. . .'}),
        }

NashBitesApp/forms/profile_form.py
from NashBitesApp.models import Profile
from django import forms


class ProfileForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = [
      'company_name', 
      'website_url', 
      'twitter_handle', 
      'instagram_handle', 
      'facebook_handle'
      ]

NashBitesApp/forms/registration_form.py
from NashBitesApp.models import Profile
from django import forms


class RegistrationForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['company_name',]
    labels = {
      'company_name': '',
    }
    widgets = {
      'company_name': forms.TextInput(attrs={'placeholder': 'Company Name'})
    }

NashBitesApp/forms/search_form.py
from django import forms


class SearchForm(forms.Form):
  search_input = forms.CharField()

NashBitesApp/forms/user_form.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
  password = forms.CharField(
    label="", widget=forms.TextInput(attrs={'type': 'password'})
  )

  class Meta:
    model = User
    fields = ['username', 'password']
    labels = {
      'username': '',
      # 'password': ''
    }
    help_texts = {
      'username': '',
    }
    widgets = {
      'username': forms.TextInput(attrs={'placeholder': 'Username'})
    }

NashBitesApp/views/home.py
from NashBitesApp.models import Location

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.conf import settings
from django import forms
import googlemaps
from django.db.models import Max
from NashBitesApp.forms import SearchForm



def HomeView(request):
    """ 
    View manages home dashboard view 
    Methods:  GET, POST
    """
    if request.method == 'GET':
        # search_input = request.GET.get('search-input', None)
        search_form = SearchForm()
        api_key = getattr(settings, 'GOOGLE_MAPS_API_KEY')
        template_name = 'home/home.html'
        # gm = googlemaps.Client(key=api_key)

        # if search_input:
        #     # Get origin: Geocode data from search input
        #     geocode_result = gm.geocode(search_input)[0]
        #     origin = geocode_result['formatted_address']
        #     geocode_result_location = geocode_result['geometry']['location']

        #     # Get destinations: create query_result = list of dictionaries of all vendor's most current timestamp location
        #     query_results = Location.objects.values().order_by('-timestamp')

        #     seen = list()
        #     destinations = []

        #     # Loop over query results
        #     for result in query_results:

        #         # If value of vendor_id is not in empty list
        #         if result['vendor_id'] not in seen:

        #             # append to destinations list
        #             destinations.append(result['address'])

        #             # then append value of vendor_id to seen list that results in having only the most current result for each vendor in destinations list
        #             seen.append(result['vendor_id'])

                
        # # Get distance data from Google based on destination and origin
        # if destinations:
        #    dist_results = gm.distance_matrix(origin, destinations)
        #    print(dist_results)
        # # make a marker for the 5 closest vendors

        #     # place marker on map

        context = {
            'api_key': api_key,
            'search_form': search_form,
            # 'search_input': search_input,
        }
        return render(request, template_name, context)

    if request.method == 'POST':
        return HttpResponseRedirect('/home/')
   

NashBitesApp/views/index.py
from django.shortcuts import render


def Welcome(request):
    template_name = 'index.html'
    context = {}
    return render(request, template_name, context)

NashBitesApp/views/locations.py
from django.shortcuts import render
from django.http import JsonResponse
from NashBitesApp.models import Location


def Location_List(request):
  """ View queries location database table data """
  locations = Location.objects.all().values()
  location_list = list(locations)
  return JsonResponse(location_list, safe=False)

NashBitesApp/views/login.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from NashBitesApp.forms import UserForm

def Login(request):
  if request.method == 'GET':
    login_form = UserForm()
    return render(request, 'registration/login.html', {'login_form': login_form})

  elif request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)

    if user is not None:
      login(request, user)
      return HttpResponseRedirect('/vendor/')

  

NashBitesApp/views/navigation.py
from django.shortcuts import render
from django.contrib.auth.models import User
from NashBitesApp.forms import SearchForm


def NavView(request):
  if request.method == 'GET':
      template_name = 'navbar.html'
      search_form = SearchForm()
      user = request.user
      context = {
        'user': user,
        'search_form': search_form,
      }
      return render(request, template_name, context)
  

NashBitesApp/views/profile.py
from NashBitesApp.forms import UserForm, ProfileForm
from django.contrib.auth.models import User
from NashBitesApp.models import Profile
from django.shortcuts import render, redirect, reverse

# @login_required
# @transaction.atomic
def ProfileView(request, username):
  if request.method == 'POST':
    user_form = UserForm(request.POST, instance=request.user)
    profile_form = ProfileForm(request.POST, instance=request.user.profile)
    
    if user_form.is_valid() and profile_form.is_valid():
      username = request.user.username
      user_form.save()
      profile_form.save()
      messages.success(request, _('Your profile was successfully updated!'))
      return redirect(reverse('website:profile', kwargs={'username': username}))
    else:
      messages.error(request, _('Please correct the error below.'))

  else:
    vendor = request.user.username
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'username': vendor
    })

NashBitesApp/views/register.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from NashBitesApp.forms import UserForm, RegistrationForm


def Register(request):
    ''' Creates a new user and initial profile data '''

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        registration_form = RegistrationForm(data=request.POST)

        if user_form.is_valid():
          
            user = user_form.save()
            profile = registration_form.save(commit=False)
            profile.vendor = user
            profile.save()

            user.set_password(user.password)
            user.save()
            login(request, user)

        return HttpResponseRedirect('/vendor/')

    elif request.method == 'GET': 
        registration_form = RegistrationForm()
        user_form = UserForm()
        context = {
          'user_form': user_form, 
          'registration_form': registration_form
          }

        return render(request, 'registration/register.html', context)

NashBitesApp/views/vendor.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.conf import settings
import googlemaps

from NashBitesApp.forms import LocationForm
from NashBitesApp.models import Location


@login_required
def VendorView(request):
    """ 
    View manages vendor dashboard view 
    Methods:  GET, POST
    """
    if request.method == 'GET':
        api_key = getattr(settings, 'GOOGLE_MAPS_API_KEY')
        template_name = 'vendor/vendor.html'
        location_list = Location.objects.filter(vendor=request.user)
        location_form = LocationForm()

        context = {
            'location_form': location_form,
            'location_list': location_list,
            'api_key': api_key
        }

        return render(request, template_name, context)

    elif request.method == 'POST':
        api_key = getattr(settings, 'GOOGLE_MAPS_API_KEY')
        location_form = LocationForm(data=request.POST)

        if location_form.is_valid():
            location = location_form.save(commit=False)
            location.vendor = request.user
            location.save()
        return HttpResponseRedirect('/vendor/')

NashBitesApp/templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Nash Eats!</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
    crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Lato|Pacifico" rel="stylesheet">
  {% block main_styles %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% endblock main_styles %}
</head>

<body>
  {% block navbar %}
  {% include 'navbar.html'%}
  {% endblock navbar %}

  {% block content %}

  {% block modal %}
  {% include 'welcome.html' %}
  {% endblock modal %}

  {% endblock %}

  {% block script_bootstrap %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  {% endblock script_bootstrap %}

  {% block script_google %}
  <script async defer src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&callback=initMap"></script>
  {% endblock script_google %}

  {% block script_maps %}
  <script src="{% static 'js/home.js' %}"></script>
  {% endblock script_maps %}

</body>

</html>

NashBitesApp/templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand"><span>Nash</span>Eats</a>

  {% if not user.is_authenticated %}

  {% block searchbar %}
    {% include 'search.html'%}
  {% endblock searchbar %}

  <div>
    <button id="btn-login" class="btn btn-outline-success my-2 my-sm-0" type="submit">
      <a class="btn-text" href="{% url 'website:login' %}"><img class="btn-img" src="{% static 'images/key.png' %}" alt=""> Login</a>
    </button>
  </div>
  
  {% endif %}


  {% if user.is_authenticated %}

  <div>
    {#<button id="btn-profile" class="btn btn-outline-success my-2 my-sm-0" type="submit"><a class="btn-text" href="{% url 'website:profile' %}">Vendor Profile</a></button>#}

    <button id="btn-logout" class="btn btn-outline-success my-2 my-sm-0" type="submit"><a class="btn-text" href="{% url 'logout' %}">Logout</a></button>
    
  </div>

  {% endif %}
</nav>

NashBitesApp/templates/profile.html
{% extends 'index.html' %}

{% load staticfiles%}

<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Save changes</button>
  </form>

NashBitesApp/templates/search.html
{% block searchbar %}

<form class="form-inline" action="{% url 'website:home' %}" class="" method="GET">
 {% csrf_token %}
 <!-- {{search_form}} -->
  <input id="address" name="search-input" class="form-control mr-sm-2" type="search" placeholder="Search food trucks here. . ." aria-label="Search" value="">
  <input class="btn btn-info" type="button" value="Search" onclick="codeAddress()">
</form>

{% endblock searchbar %}

NashBitesApp/templates/welcome.html
{% load staticfiles %}

<div class="background-welcome">

  {% block modal %}
  <div class="container welcome-modal">
    <h4 class="modal-title">Welcome to NashEats!</h4>

    <p class="modal-content">Aw, c'mon Rick. That doesn't seem so bad. It's been six hours. Dreams move one... one-hundredth the speed of reality, and dog time is one-seventh human time. So y'know, every day here is like a minute. It's like Inception, Morty, so if it's confusing and stupid, then so is everyone's favorite movie. Hmmm, human music. You're growing up fast, Morty. You're going into a great big thorn straight into my ass. </p>


  
    <h5 class="modal-enter">Enter Here</h5>
    <a class="modal-link" href="{% url 'website:home'%}">
      <img class="" src="{% static 'images/checkmark.png' %}" alt="">
    </a>
  
  
  
  </div>
  {% endblock modal %}

</div>